default_context:
  project_name: 'test'
  project_slug: 'test'
  domain_main: 'test.com'
  domain_staging: 'stag.test.com'
  docker_swarm_stack_name_main: 'test-com'
  docker_swarm_stack_name_staging: 'stag-test-com'
  secret_key: '9a37a516db02ab252ce00899ee3436ca722491845c2a5181d149482c8006e5a7'
  first_superuser: 'admin@test.com'
  first_superuser_password: '68206c731caa65c8ea9b79eb91648088a54919fed17e17f9b7382c36f2e5e09e'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.test.com", "https://stag.test.com", "https://test.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@test.com'
  postgres_password: 'fdaf3c0d79765771ed986749f7beb24233448b36df49b38f3290124f7866e1fb'
  pgadmin_default_user: 'admin@test.com'
  pgadmin_default_user_password: 'de7622823921e55f600447786e4adf848a37e1ea66aaaf45e97504c84d715f41'
  traefik_constraint_tag: 'test.com'
  traefik_constraint_tag_staging: 'stag.test.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:68206c731caa65c8ea9b79eb91648088a54919fed17e17f9b7382c36f2e5e09e'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
